# Generated by Django 3.2.7 on 2021-10-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculo',
            old_name='senteca',
            new_name='sentenca',
        ),
        migrations.AlterField(
            model_name='calculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
